"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { ReleaseCompletionOverview } from "../../server/commercial-release-api";
import type { TenantFleetItem } from "../../server/tenant-fleet-api";

type Row = Readonly<Record<string, unknown>>;
function field<T=unknown>(row:Row|undefined,key:string):T|undefined{return row?.[key] as T|undefined;}
function text(row:Row|undefined,key:string):string{const value=field(row,key);return value===null||value===undefined?"":String(value);}
function number(row:Row|undefined,key:string):number{const value=Number(field(row,key)??0);return Number.isFinite(value)?value:0;}
function date(value:unknown):string{if(!value||Number.isNaN(Date.parse(String(value))))return"Not recorded";return new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Johannesburg"}).format(new Date(String(value)));}
function human(value:string):string{return value.replaceAll(/[._-]+/g," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());}
function Pill({value}:{value:string}){return <span className={`release-pill ${value||"unknown"}`}>{human(value||"unknown")}</span>;}
function jsonArray(value:FormDataEntryValue|null):unknown[]{const parsed=JSON.parse(String(value??"[]")) as unknown;if(!Array.isArray(parsed))throw new Error("Expected a JSON array");return parsed;}

async function mutate(operation:string,body:Readonly<Record<string,unknown>>){const response=await fetch(`/api/releases/${operation}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":`release-${crypto.randomUUID()}`},body:JSON.stringify(body)});const result=await response.json() as Record<string,unknown>&{message?:string};if(!response.ok)throw new Error(result.message??"Release operation failed");return result;}

export function ReleaseManagementWorkspace({release,tenants}:{release:ReleaseCompletionOverview;tenants:readonly TenantFleetItem[]}){
 const router=useRouter();const[error,setError]=useState<string>();const[message,setMessage]=useState<string>();const[busy,setBusy]=useState<string>();
 const activeTargets=release.targets.filter((item)=>["planned","active","paused"].includes(text(item,"lifecycle")));
 const canaries=release.assignments.filter((item)=>Boolean(field(item,"isCanary")));
 const blockedMigrations=release.migrations.filter((item)=>["blocked","failed"].includes(text(item,"state")));
 async function run(operation:string,body:Readonly<Record<string,unknown>>,success:string){setBusy(operation);setError(undefined);setMessage(undefined);try{await mutate(operation,body);setMessage(success);router.refresh();return true;}catch(cause){setError(cause instanceof Error?cause.message:"Release operation failed");return false;}finally{setBusy(undefined);}}
 async function transitionVersion(item:Row,lifecycle:string){const reason=window.prompt(`Record why release ${text(item,"versionKey")} is becoming ${lifecycle}.`);if(!reason||reason.trim().length<10){setError("A reason of at least 10 characters is required.");return;}await run(`version:${text(item,"versionKey")}:transition`,{lifecycle,expectedVersion:number(item,"version"),reason},`Release ${lifecycle} recorded.`);}
 async function transitionTarget(item:Row,lifecycle:string){const reason=window.prompt(`Record why this ring target is becoming ${lifecycle}.`);if(!reason||reason.trim().length<10){setError("A reason of at least 10 characters is required.");return;}await run(`target:${text(item,"id")}:transition`,{lifecycle,expectedVersion:number(item,"version"),reason},`Ring target ${lifecycle} recorded.`);}
 async function createVersion(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(await run("version:create",{versionKey:String(data.get("versionKey")),displayName:String(data.get("displayName")),releaseNotes:String(data.get("releaseNotes")),compatibilityFloor:String(data.get("compatibilityFloor")??"")||undefined,schemaVersion:Number(data.get("schemaVersion")),migrationBundleKey:String(data.get("migrationBundleKey")),migrationState:String(data.get("migrationState")),artifactDigest:String(data.get("artifactDigest")),sourceCommitSha:String(data.get("sourceCommitSha"))},"Release version registered."))form.reset();}
 async function createTarget(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(await run("target:create",{ringKey:String(data.get("ringKey")),releaseVersion:String(data.get("releaseVersion")),rolloutPercent:Number(data.get("rolloutPercent")),effectiveFrom:new Date(String(data.get("effectiveFrom"))).toISOString(),effectiveUntil:data.get("effectiveUntil")?new Date(String(data.get("effectiveUntil"))).toISOString():undefined,reason:String(data.get("reason"))},"Release ring target planned."))form.reset();}
 async function createFlag(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(await run("flag:create",{key:String(data.get("key")),displayName:String(data.get("displayName")),description:String(data.get("description")),riskLevel:String(data.get("riskLevel")),defaultEnabled:data.get("defaultEnabled")==="on",requiredModuleKey:String(data.get("requiredModuleKey")??"")||undefined,reason:String(data.get("reason"))},"Feature flag created in draft state."))form.reset();}
 async function flagLifecycle(item:Row,lifecycle:string){const reason=window.prompt(`Record why ${text(item,"key")} is becoming ${lifecycle}.`);if(!reason||reason.trim().length<20){setError("Feature flag changes require a reason of at least 20 characters.");return;}await run(`flag:${text(item,"key")}:lifecycle`,{lifecycle,expectedVersion:number(item,"version"),reason},`Feature flag ${lifecycle} recorded.`);}
 async function configureRingFlag(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const ringKey=String(data.get("ringKey"));const flagKey=String(data.get("flagKey"));const current=release.ringFeatureFlags.find((item)=>text(item,"ringKey")===ringKey&&text(item,"featureFlagKey")===flagKey);if(await run(`ring:${ringKey}:flag:${flagKey}`,{enabled:String(data.get("enabled"))==="true",expectedVersion:number(current,"version"),reason:String(data.get("reason"))},"Ring feature configuration updated."))form.reset();}
 async function assignRing(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const tenantId=String(data.get("tenantId"));const current=release.assignments.find((item)=>text(item,"tenantId")===tenantId);if(await run(`tenant:${tenantId}:ring`,{ringKey:String(data.get("ringKey")),isCanary:data.get("isCanary")==="on",effectiveFrom:new Date(String(data.get("effectiveFrom"))).toISOString(),effectiveUntil:data.get("effectiveUntil")?new Date(String(data.get("effectiveUntil"))).toISOString():undefined,expectedVersion:number(current,"version"),reason:String(data.get("reason"))},"Tenant release assignment updated."))form.reset();}
 async function setException(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(await run("exception:set",{tenantId:String(data.get("tenantId")),pinnedReleaseVersion:String(data.get("pinnedReleaseVersion")??"")||undefined,excludedReleaseVersion:String(data.get("excludedReleaseVersion")??"")||undefined,effectiveFrom:new Date(String(data.get("effectiveFrom"))).toISOString(),effectiveUntil:data.get("effectiveUntil")?new Date(String(data.get("effectiveUntil"))).toISOString():undefined,reason:String(data.get("reason"))},"Tenant rollout exception recorded."))form.reset();}
 async function compatibility(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{if(await run("compatibility:record",{tenantId:String(data.get("tenantId")),currentReleaseVersion:String(data.get("currentReleaseVersion")??"")||undefined,targetReleaseVersion:String(data.get("targetReleaseVersion")),compatible:String(data.get("compatible"))==="true",blockers:jsonArray(data.get("blockers")),warnings:jsonArray(data.get("warnings")),evidence:{source:String(data.get("source"))},checkedBy:String(data.get("checkedBy"))},"Compatibility evidence recorded."))form.reset();}catch(cause){setError(cause instanceof Error?cause.message:"Compatibility evidence is invalid.");}}
 async function migration(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const tenantId=String(data.get("tenantId"));const version=String(data.get("targetReleaseVersion"));const current=release.migrations.find((item)=>text(item,"tenantId")===tenantId&&text(item,"targetReleaseVersion")===version);if(await run("migration:update",{tenantId,targetReleaseVersion:version,state:String(data.get("state")),currentStep:String(data.get("currentStep")??"")||undefined,completedSteps:String(data.get("completedSteps")??"").split(",").map((item)=>item.trim()).filter(Boolean),lastError:String(data.get("lastError")??"")||undefined,evidence:{runReference:String(data.get("runReference")??"")},updatedBy:String(data.get("updatedBy")),expectedVersion:number(current,"version")||1},"Tenant migration evidence updated."))form.reset();}
 async function rollback(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(await run("rollback:create",{ringKey:String(data.get("ringKey")??"")||undefined,tenantId:String(data.get("tenantId")??"")||undefined,fromReleaseVersion:String(data.get("fromReleaseVersion")),toReleaseVersion:String(data.get("toReleaseVersion")),effectiveAt:new Date(String(data.get("effectiveAt"))).toISOString(),reason:String(data.get("reason"))},"Rollback decision recorded and projected."))form.reset();}
 return <section className="release-management" aria-labelledby="release-title">
  <header className="release-heading"><div><p className="cp-eyebrow">RELEASE CONTROL</p><h1 id="release-title">Release management</h1><p>Version compatibility, feature policy, rollout rings, canaries, migrations, exceptions and rollback.</p></div><div className="release-generated"><small>Snapshot generated</small><strong>{date(release.generatedAt)}</strong></div></header>
  <div className="release-boundary"><strong>Progressive delivery with evidence</strong><p>A release cannot become active until its migration bundle is ready. Ring targets require independent activation, canaries are explicit tenant assignments, and rollback decisions create durable recovery state.</p></div>
  <section className="release-summary"><article><small>Release versions</small><strong>{release.versions.length}</strong><span>Registered artifacts</span></article><article><small>Open ring targets</small><strong>{activeTargets.length}</strong><span>Planned, active or paused</span></article><article><small>Canary tenants</small><strong>{canaries.length}</strong><span>Explicitly designated</span></article><article className={blockedMigrations.length?"critical":undefined}><small>Blocked migrations</small><strong>{blockedMigrations.length}</strong><span>Requires operator action</span></article></section>
  {error?<p className="release-feedback error" role="alert">{error}</p>:null}{message?<p className="release-feedback success" role="status">{message}</p>:null}
  <nav className="release-index"><a href="#versions">Versions</a><a href="#rings">Rings</a><a href="#flags">Feature flags</a><a href="#canaries">Canaries</a><a href="#compatibility">Compatibility</a><a href="#migrations">Migrations</a><a href="#exceptions">Exceptions</a><a href="#rollback">Rollback</a></nav>

  <section id="versions" className="release-section"><header><div><p className="cp-eyebrow">RELEASE VERSIONS</p><h2>Artifacts and compatibility floor</h2></div><span>{release.versions.length}</span></header><div className="release-table-wrap"><table><thead><tr><th>Version</th><th>Lifecycle</th><th>Schema and migration</th><th>Artifact</th><th>Approval</th><th>Actions</th></tr></thead><tbody>{release.versions.map((item)=>{const lifecycle=text(item,"lifecycle");return <tr key={text(item,"versionKey")}><td><strong>{text(item,"displayName")}</strong><small>{text(item,"versionKey")} · floor {text(item,"compatibilityFloor")||"none"}</small></td><td><Pill value={lifecycle}/></td><td>Schema {number(item,"schemaVersion")}<small>{text(item,"migrationBundleKey")} · {human(text(item,"migrationState"))}</small></td><td><code>{text(item,"artifactDigest")}</code><small>{text(item,"sourceCommitSha")}</small></td><td>{text(item,"approvedBy")?`Approved ${date(field(item,"approvedAt"))}`:"Independent approval required"}</td><td><div className="release-row-actions">{lifecycle==="draft"?<button onClick={()=>transitionVersion(item,"candidate")}>Approve candidate</button>:null}{lifecycle==="candidate"?<><button onClick={()=>transitionVersion(item,"active")}>Activate</button><button className="danger" onClick={()=>transitionVersion(item,"retired")}>Retire</button></>:null}{lifecycle==="active"?<><button onClick={()=>transitionVersion(item,"retired")}>Retire</button><button className="danger" onClick={()=>transitionVersion(item,"rolled-back")}>Mark rolled back</button></>:null}</div></td></tr>;})}</tbody></table></div><form className="release-form" onSubmit={createVersion}><h3>Register immutable release artifact</h3><div className="release-form-grid three"><label>Version<input name="versionKey" required placeholder="1.8.0"/></label><label>Display name<input name="displayName" required/></label><label>Compatibility floor<input name="compatibilityFloor" placeholder="1.7.0"/></label></div><label>Release notes<textarea name="releaseNotes" required minLength={20}/></label><div className="release-form-grid three"><label>Schema version<input name="schemaVersion" type="number" min="1" required/></label><label>Migration bundle<input name="migrationBundleKey" required/></label><label>Migration state<select name="migrationState"><option value="pending">Pending</option><option value="running">Running</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="not-required">Not required</option></select></label></div><label>Artifact digest<input name="artifactDigest" required placeholder="sha256:64 lowercase hex characters"/></label><label>Source commit SHA<input name="sourceCommitSha" required/></label><button disabled={Boolean(busy)}>Register release</button></form></section>

  <section id="rings" className="release-section"><header><div><p className="cp-eyebrow">ROLLOUT RINGS</p><h2>Progressive target policy</h2></div><span>{release.rings.length}</span></header><div className="release-ring-grid">{release.rings.map((ring)=><article key={text(ring,"key")}><header><div><small>Sequence {number(ring,"sequence")}</small><h3>{text(ring,"displayName")}</h3></div><Pill value={text(ring,"lifecycle")}/></header><p>{text(ring,"description")}</p><dl><div><dt>Target</dt><dd>{text(ring,"targetVersion")||"Not targeted"}</dd></div><div><dt>Tenants</dt><dd>{number(ring,"tenantCount")}</dd></div><div><dt>Canaries</dt><dd>{number(ring,"canaryCount")}</dd></div></dl></article>)}</div><div className="release-table-wrap"><table><thead><tr><th>Ring target</th><th>Rollout</th><th>Lifecycle</th><th>Compatibility</th><th>Effective period</th><th>Actions</th></tr></thead><tbody>{release.targets.map((item)=>{const lifecycle=text(item,"lifecycle");return <tr key={text(item,"id")}><td>{text(item,"ringName")}<small>{text(item,"releaseVersion")}</small></td><td>{number(item,"rolloutPercent").toFixed(2)}%</td><td><Pill value={lifecycle}/></td><td>{number(item,"compatibleTenants")} compatible<small>{number(item,"blockedTenants")} blocked</small></td><td>{date(field(item,"effectiveFrom"))}<small>Until {date(field(item,"effectiveUntil"))}</small></td><td><div className="release-row-actions">{["planned","paused"].includes(lifecycle)?<button onClick={()=>transitionTarget(item,"active")}>Activate</button>:null}{lifecycle==="active"?<><button onClick={()=>transitionTarget(item,"paused")}>Pause</button><button onClick={()=>transitionTarget(item,"completed")}>Complete</button></>:null}{["planned","active","paused"].includes(lifecycle)?<button className="danger" onClick={()=>transitionTarget(item,"rolled-back")}>Roll back</button>:null}</div></td></tr>;})}</tbody></table></div><form className="release-form compact" onSubmit={createTarget}><h3>Plan release ring target</h3><div className="release-form-grid three"><label>Ring<select name="ringKey" required>{release.rings.map((ring)=><option key={text(ring,"key")} value={text(ring,"key")}>{text(ring,"displayName")}</option>)}</select></label><label>Release<select name="releaseVersion" required>{release.versions.filter((item)=>["candidate","active"].includes(text(item,"lifecycle"))).map((item)=><option key={text(item,"versionKey")} value={text(item,"versionKey")}>{text(item,"versionKey")}</option>)}</select></label><label>Rollout percent<input name="rolloutPercent" type="number" min="0.01" max="100" step="0.01" defaultValue="100" required/></label></div><div className="release-form-grid"><label>Effective from<input name="effectiveFrom" type="datetime-local" required/></label><label>Effective until<input name="effectiveUntil" type="datetime-local"/></label></div><label>Reason<textarea name="reason" required minLength={10}/></label><button>Plan target</button></form></section>

  <section id="flags" className="release-section"><header><div><p className="cp-eyebrow">FEATURE POLICY</p><h2>Flags and ring configuration</h2></div><span>{release.featureFlags.length}</span></header><div className="release-table-wrap"><table><thead><tr><th>Feature</th><th>Risk</th><th>Lifecycle</th><th>Default</th><th>Entitlement</th><th>Actions</th></tr></thead><tbody>{release.featureFlags.map((item)=><tr key={text(item,"key")}><td><strong>{text(item,"displayName")}</strong><small>{text(item,"key")}: {text(item,"description")}</small></td><td><Pill value={text(item,"riskLevel")}/></td><td><Pill value={text(item,"lifecycle")}/></td><td>{field(item,"defaultEnabled")?"Enabled":"Disabled"}</td><td>{text(item,"requiredModuleKey")||"None"}</td><td><div className="release-row-actions">{text(item,"lifecycle")==="draft"?<button onClick={()=>flagLifecycle(item,"active")}>Activate</button>:null}{text(item,"lifecycle")==="active"?<button className="danger" onClick={()=>flagLifecycle(item,"retired")}>Retire</button>:null}</div></td></tr>)}</tbody></table></div><div className="release-form-columns"><form className="release-form compact" onSubmit={createFlag}><h3>Create feature flag</h3><label>Key<input name="key" required/></label><label>Display name<input name="displayName" required/></label><label>Description<textarea name="description" required minLength={20}/></label><div className="release-form-grid"><label>Risk<select name="riskLevel"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Required module<input name="requiredModuleKey"/></label></div><label className="release-check"><input name="defaultEnabled" type="checkbox"/> Enabled by default</label><label>Reason<textarea name="reason" required minLength={20}/></label><button>Create draft flag</button></form><form className="release-form compact" onSubmit={configureRingFlag}><h3>Configure flag for ring</h3><label>Ring<select name="ringKey">{release.rings.map((ring)=><option key={text(ring,"key")} value={text(ring,"key")}>{text(ring,"displayName")}</option>)}</select></label><label>Feature flag<select name="flagKey">{release.featureFlags.filter((item)=>text(item,"lifecycle")==="active").map((item)=><option key={text(item,"key")} value={text(item,"key")}>{text(item,"displayName")}</option>)}</select></label><label>State<select name="enabled"><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label>Reason<textarea name="reason" required minLength={20}/></label><button>Save ring flag</button></form></div></section>

  <section id="canaries" className="release-section"><header><div><p className="cp-eyebrow">TENANT ROLLOUT</p><h2>Canaries and ring assignments</h2></div><span>{canaries.length} canaries</span></header><div className="release-table-wrap"><table><thead><tr><th>Tenant</th><th>Ring</th><th>Canary</th><th>Effective period</th><th>Reason</th></tr></thead><tbody>{release.assignments.map((item)=><tr key={text(item,"tenantId")}><td>{text(item,"tenantName")}<small>{text(item,"tenantId")}</small></td><td>{text(item,"ringKey")}</td><td>{field(item,"isCanary")?<Pill value="canary"/>:"Standard"}</td><td>{date(field(item,"effectiveFrom"))}<small>Until {date(field(item,"effectiveUntil"))}</small></td><td>{text(item,"reason")}</td></tr>)}</tbody></table></div><form className="release-form compact" onSubmit={assignRing}><h3>Assign tenant rollout ring</h3><div className="release-form-grid"><label>Tenant<select name="tenantId" required><option value="">Select institution</option>{tenants.map((tenant)=><option key={tenant.id} value={tenant.id}>{tenant.displayName}</option>)}</select></label><label>Ring<select name="ringKey">{release.rings.filter((ring)=>text(ring,"lifecycle")==="active").map((ring)=><option key={text(ring,"key")} value={text(ring,"key")}>{text(ring,"displayName")}</option>)}</select></label></div><label className="release-check"><input name="isCanary" type="checkbox"/> Designate tenant as explicit canary</label><div className="release-form-grid"><label>Effective from<input name="effectiveFrom" type="datetime-local" required/></label><label>Effective until<input name="effectiveUntil" type="datetime-local"/></label></div><label>Reason<textarea name="reason" required minLength={20}/></label><button>Save rollout assignment</button></form></section>

  <section id="compatibility" className="release-section"><header><div><p className="cp-eyebrow">VERSION COMPATIBILITY</p><h2>Tenant readiness evidence</h2></div><span>{release.compatibility.length}</span></header><div className="release-table-wrap"><table><thead><tr><th>Tenant</th><th>Version path</th><th>Compatible</th><th>Blockers and warnings</th><th>Checked</th></tr></thead><tbody>{release.compatibility.map((item)=><tr key={text(item,"id")}><td>{text(item,"tenantName")}</td><td>{text(item,"currentReleaseVersion")||"Unknown"} → {text(item,"targetReleaseVersion")}</td><td><Pill value={field(item,"compatible")?"compatible":"blocked"}/></td><td><code>{JSON.stringify(field(item,"blockers")??[])}</code><small>{JSON.stringify(field(item,"warnings")??[])}</small></td><td>{date(field(item,"checkedAt"))}<small>{text(item,"checkedBy")}</small></td></tr>)}</tbody></table></div><form className="release-form compact" onSubmit={compatibility}><h3>Record compatibility result</h3><div className="release-form-grid"><label>Tenant<select name="tenantId" required>{tenants.map((tenant)=><option key={tenant.id} value={tenant.id}>{tenant.displayName}</option>)}</select></label><label>Target release<select name="targetReleaseVersion">{release.versions.map((item)=><option key={text(item,"versionKey")} value={text(item,"versionKey")}>{text(item,"versionKey")}</option>)}</select></label></div><label>Current release<input name="currentReleaseVersion"/></label><label>Result<select name="compatible"><option value="true">Compatible</option><option value="false">Blocked</option></select></label><label>Blockers JSON<textarea name="blockers" defaultValue="[]"/></label><label>Warnings JSON<textarea name="warnings" defaultValue="[]"/></label><div className="release-form-grid"><label>Checked by<input name="checkedBy" required placeholder="compatibility-worker"/></label><label>Source<input name="source" required placeholder="preflight-run-id"/></label></div><button>Record compatibility</button></form></section>

  <section id="migrations" className="release-section"><header><div><p className="cp-eyebrow">MIGRATION STATUS</p><h2>Tenant execution evidence</h2></div><span>{release.migrations.length}</span></header><div className="release-table-wrap"><table><thead><tr><th>Tenant</th><th>Target</th><th>State</th><th>Progress</th><th>Error</th><th>Updated</th></tr></thead><tbody>{release.migrations.map((item)=><tr key={`${text(item,"tenantId")}:${text(item,"targetReleaseVersion")}`}><td>{text(item,"tenantName")}</td><td>{text(item,"targetReleaseVersion")}</td><td><Pill value={text(item,"state")}/></td><td>{text(item,"currentStep")||"Not started"}<small>{(field<string[]>(item,"completedSteps")??[]).join(", ")}</small></td><td>{text(item,"lastError")||"None"}</td><td>{date(field(item,"updatedAt"))}<small>v{number(item,"version")}</small></td></tr>)}</tbody></table></div><form className="release-form compact" onSubmit={migration}><h3>Update tenant migration evidence</h3><div className="release-form-grid"><label>Tenant<select name="tenantId" required>{tenants.map((tenant)=><option key={tenant.id} value={tenant.id}>{tenant.displayName}</option>)}</select></label><label>Target release<select name="targetReleaseVersion">{release.versions.map((item)=><option key={text(item,"versionKey")} value={text(item,"versionKey")}>{text(item,"versionKey")}</option>)}</select></label></div><div className="release-form-grid"><label>State<select name="state"><option value="pending">Pending</option><option value="running">Running</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="rolled-back">Rolled back</option></select></label><label>Updated by<input name="updatedBy" required placeholder="migration-worker"/></label></div><label>Current step<input name="currentStep"/></label><label>Completed steps<input name="completedSteps" placeholder="backup, schema, projection"/></label><label>Last error<textarea name="lastError"/></label><label>Run reference<input name="runReference"/></label><button>Update migration</button></form></section>

  <section id="exceptions" className="release-section"><header><div><p className="cp-eyebrow">TENANT EXCEPTIONS</p><h2>Pinning and exclusion windows</h2></div><span>{release.exceptions.length}</span></header><div className="release-table-wrap"><table><thead><tr><th>Tenant</th><th>Pin</th><th>Exclude</th><th>State</th><th>Effective period</th><th>Reason</th></tr></thead><tbody>{release.exceptions.map((item)=><tr key={text(item,"id")}><td>{text(item,"tenantName")}</td><td>{text(item,"pinnedReleaseVersion")||"None"}</td><td>{text(item,"excludedReleaseVersion")||"None"}</td><td><Pill value={text(item,"state")}/></td><td>{date(field(item,"effectiveFrom"))}<small>Until {date(field(item,"effectiveUntil"))}</small></td><td>{text(item,"reason")}</td></tr>)}</tbody></table></div><form className="release-form compact" onSubmit={setException}><h3>Record tenant rollout exception</h3><label>Tenant<select name="tenantId" required>{tenants.map((tenant)=><option key={tenant.id} value={tenant.id}>{tenant.displayName}</option>)}</select></label><div className="release-form-grid"><label>Pinned release<input name="pinnedReleaseVersion"/></label><label>Excluded release<input name="excludedReleaseVersion"/></label></div><div className="release-form-grid"><label>Effective from<input name="effectiveFrom" type="datetime-local" required/></label><label>Effective until<input name="effectiveUntil" type="datetime-local"/></label></div><label>Reason<textarea name="reason" required minLength={10}/></label><button>Save exception</button></form></section>

  <section id="rollback" className="release-section"><header><div><p className="cp-eyebrow">ROLLBACK CONTROL</p><h2>Approved recovery decisions</h2></div><span>{release.rollbacks.length}</span></header><div className="release-table-wrap"><table><thead><tr><th>Scope</th><th>Version path</th><th>State</th><th>Effective</th><th>Reason</th></tr></thead><tbody>{release.rollbacks.map((item)=><tr key={text(item,"id")}><td>{text(item,"tenantName")||text(item,"ringKey")}</td><td>{text(item,"fromReleaseVersion")} → {text(item,"toReleaseVersion")}</td><td><Pill value={text(item,"state")}/></td><td>{date(field(item,"effectiveAt"))}</td><td>{text(item,"reason")}</td></tr>)}</tbody></table></div><form className="release-form rollback" onSubmit={rollback}><h3>Approve rollback</h3><div className="release-form-grid"><label>Ring<select name="ringKey"><option value="">Tenant-specific</option>{release.rings.map((ring)=><option key={text(ring,"key")} value={text(ring,"key")}>{text(ring,"displayName")}</option>)}</select></label><label>Tenant<select name="tenantId"><option value="">Ring-wide</option>{tenants.map((tenant)=><option key={tenant.id} value={tenant.id}>{tenant.displayName}</option>)}</select></label></div><div className="release-form-grid"><label>From release<input name="fromReleaseVersion" required/></label><label>To release<input name="toReleaseVersion" required/></label></div><label>Effective at<input name="effectiveAt" type="datetime-local" required/></label><label>Reason<textarea name="reason" required minLength={10}/></label><button className="danger">Approve rollback</button></form></section>
 </section>;
}
