"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { DuplicateCandidatePage } from "@veza/contracts";

export function DuplicateReview({ page }: { page: DuplicateCandidatePage }) {
  const router = useRouter(); const [busy,setBusy]=useState<string>(); const [message,setMessage]=useState("");
  async function decide(id:string,decision:"confirmed-duplicate"|"not-duplicate"){setBusy(id);setMessage("");const response=await fetch(`/api/people/duplicates/${id}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,reason:decision==="confirmed-duplicate"?"Reviewed matching identity evidence and approved this pair for controlled merge.":"Reviewed identity evidence and confirmed these are separate institutional people."})});const body=await response.json() as {message?:string};if(!response.ok){setMessage(body.message??"Decision failed");setBusy(undefined);return;}router.refresh();}
  async function merge(candidate:DuplicateCandidatePage["items"][number]){setBusy(candidate.id);setMessage("");const response=await fetch("/api/people/merges",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourcePersonId:candidate.rightPerson.id,targetPersonId:candidate.leftPerson.id,sourceExpectedVersion:candidate.rightPerson.version,targetExpectedVersion:candidate.leftPerson.version,reason:"Reviewed duplicate evidence and selected the left-hand canonical record as the surviving institutional person."})});const body=await response.json() as {message?:string};if(!response.ok){setMessage(body.message??"Merge failed");setBusy(undefined);return;}router.refresh();}
  return <div className="people-workspace"><header className="people-heading"><div><p>IDENTITY RECONCILIATION</p><h1>Duplicate review</h1><span>Review evidence, confirm distinct people, or complete an MFA-protected reversible merge.</span></div><Link className="people-primary" href="/people">Back to directory</Link></header>{message?<p className="people-error" role="alert">{message}</p>:null}<section className="duplicate-grid">{page.items.length?page.items.map(candidate=><article className="duplicate-card" key={candidate.id}><header><span>{Math.round(candidate.matchScore*100)}% match</span><small>{new Date(candidate.createdAt).toLocaleDateString("en-ZA")}</small></header><div className="duplicate-people"><div><strong>{candidate.leftPerson.displayName}</strong><Link href={`/people/${candidate.leftPerson.id}`}>Open record</Link></div><b>↔</b><div><strong>{candidate.rightPerson.displayName}</strong><Link href={`/people/${candidate.rightPerson.id}`}>Open record</Link></div></div><pre>{JSON.stringify(candidate.reasons,null,2)}</pre><footer><button disabled={busy===candidate.id} onClick={()=>decide(candidate.id,"not-duplicate")}>Keep separate</button><button disabled={busy===candidate.id} onClick={()=>decide(candidate.id,"confirmed-duplicate")}>Approve merge</button><button className="danger" disabled={busy===candidate.id} onClick={()=>merge(candidate)}>Merge now</button></footer></article>):<div className="people-empty"><strong>No duplicate candidates need review</strong><p>Exact email matches and strong identity similarities will appear here automatically.</p></div>}</section>{page.page.nextCursor?<Link className="people-next" href={`/people/duplicates?cursor=${encodeURIComponent(page.page.nextCursor)}`}>View more candidates →</Link>:null}</div>;
}
