"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import type { PersonDetail, WorkspaceSession } from "@veza/contracts";

function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium", timeZone: "Africa/Johannesburg" }).format(new Date(value)) : "Not recorded"; }
function stateLabel(value?: string) { return value ? value.replaceAll("-", " ") : "Not configured"; }

function ProfileForm({ person, institutionId, kind }: { person: PersonDetail; institutionId?: string; kind: "learner" | "staff" }) {
  const router = useRouter(); const [state, setState] = useState<"idle" | "saving" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!institutionId) return; setState("saving"); setMessage(""); const form = new FormData(event.currentTarget); const payload = kind === "learner" ? { expectedPersonVersion: person.version, status: String(form.get("status")), admissionDate: String(form.get("startDate") || "") || undefined, completionDate: String(form.get("endDate") || "") || undefined } : { expectedPersonVersion: person.version, status: String(form.get("status")), employeeNumber: String(form.get("employeeNumber") || "") || undefined, engagementType: String(form.get("engagementType") || "employee") }; const response = await fetch(`/api/people/${person.id}/${kind}-profile`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ institutionId, ...payload }) }); const body = await response.json() as { message?: string }; if (!response.ok) { setState("error"); setMessage(body.message ?? "Profile could not be updated"); return; } setState("idle"); router.refresh(); }
  const profile = kind === "learner" ? person.learner : person.staff;
  return <form className="person-panel person-profile-form" onSubmit={submit}><header><div><p>{kind.toUpperCase()} PROFILE</p><h2>{kind === "learner" ? "Learner lifecycle" : "Staff engagement"}</h2></div><span className={profile ? "configured" : "missing"}>{profile ? "Configured" : "Missing"}</span></header><label>Status<select name="status" defaultValue={profile?.status ?? (kind === "learner" ? "applicant" : "active")}>{kind === "learner" ? <><option value="applicant">Applicant</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="withdrawn">Withdrawn</option><option value="completed">Completed</option></> : <><option value="active">Active</option><option value="leave">On leave</option><option value="suspended">Suspended</option><option value="ended">Ended</option></>}</select></label>{kind === "learner" ? <><label>Admission date<input type="date" name="startDate" defaultValue={person.learner?.admissionDate}/></label><label>Completion or exit date<input type="date" name="endDate" defaultValue={person.learner?.completionDate}/></label></> : <><label>Employee number<input name="employeeNumber" maxLength={80} defaultValue={person.staff?.employeeNumber}/></label><label>Engagement<select name="engagementType" defaultValue={person.staff?.engagementType ?? "employee"}><option value="employee">Employee</option><option value="contractor">Contractor</option><option value="volunteer">Volunteer</option><option value="external">External</option></select></label></>}{message ? <p className="people-error" role="alert">{message}</p> : null}<button disabled={!institutionId || state === "saving"}>{state === "saving" ? "Saving…" : "Save profile"}</button></form>;
}

function RelationshipForm({ person }: { person: PersonDetail }) {
  const router = useRouter(); const [state, setState] = useState<"idle" | "saving" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("saving"); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/people/${person.id}/relationships`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ relatedPersonId: String(form.get("relatedPersonId")), type: String(form.get("type")), startsOn: String(form.get("startsOn")), canReceiveCommunications: form.get("communications") === "on", canAccessRecords: form.get("records") === "on" }) }); const body = await response.json() as { message?: string }; if (!response.ok) { setState("error"); setMessage(body.message ?? "Relationship could not be created"); return; } event.currentTarget.reset(); setState("idle"); router.refresh(); }
  return <form className="person-panel relationship-form" onSubmit={submit}><header><div><p>AUTHORISED RELATIONSHIP</p><h2>Add guardian or contact</h2></div></header><label>Related person ID<input name="relatedPersonId" required pattern="[0-9a-fA-F-]{36}" placeholder="Existing person UUID"/></label><label>Relationship<select name="type"><option value="guardian">Guardian</option><option value="authorised-contact">Authorised contact</option><option value="sponsor">Sponsor</option><option value="employer">Employer</option><option value="advisor">Advisor</option></select></label><label>Starts on<input type="date" name="startsOn" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="inline-check"><input type="checkbox" name="communications"/> May receive communications</label><label className="inline-check"><input type="checkbox" name="records"/> May access permitted records</label>{message ? <p className="people-error" role="alert">{message}</p> : null}<button disabled={state === "saving"}>{state === "saving" ? "Creating…" : "Create relationship"}</button></form>;
}

export function PersonRecord({ person, session }: { person: PersonDetail; session: WorkspaceSession }) {
  const institutionId = session.membership.institutionIds[0];
  return <div className="person-record"><header className="person-record-heading"><div><Link href="/people">← Institution directory</Link><p>PERSON RECORD · VERSION {person.version}</p><h1>{person.displayName}</h1><span>{person.primaryEmail ?? "No primary email"} · {stateLabel(person.status)}</span></div><div className="person-record-version"><small>Last authoritative update</small><strong>{formatDate(person.updatedAt)}</strong></div></header><section className="person-overview"><article><span>Legal name</span><strong>{person.givenName} {person.familyName}</strong></article><article><span>Date of birth</span><strong>{formatDate(person.dateOfBirth)}</strong></article><article><span>Learner state</span><strong>{stateLabel(person.learner?.status)}</strong></article><article><span>Staff state</span><strong>{stateLabel(person.staff?.status)}</strong></article></section><div className="person-grid"><ProfileForm person={person} institutionId={institutionId} kind="learner"/><ProfileForm person={person} institutionId={institutionId} kind="staff"/><section className="person-panel relationship-list"><header><div><p>RELATIONSHIP AUTHORITY</p><h2>Guardians and contacts</h2></div><span>{person.relationships.length}</span></header>{person.relationships.length ? <ul>{person.relationships.map((relationship) => <li key={relationship.id}><div><strong>{stateLabel(relationship.type)}</strong><small>{relationship.relatedPersonId}</small></div><span className={relationship.status}>{relationship.status}</span><dl><div><dt>Communications</dt><dd>{relationship.canReceiveCommunications ? "Allowed" : "No"}</dd></div><div><dt>Record access</dt><dd>{relationship.canAccessRecords ? "Allowed" : "No"}</dd></div><div><dt>Effective</dt><dd>{formatDate(relationship.startsOn)}</dd></div></dl></li>)}</ul> : <div className="person-empty">No guardian, sponsor or authorised-contact relationships recorded.</div>}</section><RelationshipForm person={person}/></div><section className="person-panel contact-panel"><header><div><p>CONTACT EVIDENCE</p><h2>Contact points</h2></div><span>{person.contacts.length}</span></header><div className="contact-grid">{person.contacts.map((contact) => <article key={contact.id}><span>{contact.type}</span><strong>{contact.value}</strong><small>{contact.isPrimary ? "Primary" : contact.label ?? "Secondary"} · {contact.verifiedAt ? `Verified ${formatDate(contact.verifiedAt)}` : "Not verified"}</small></article>)}</div></section></div>;
}
