"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { CommercialGovernanceOverview } from "../../server/commercial-release-api";
import type { TenantFleetItem } from "../../server/tenant-fleet-api";

type Row = Readonly<Record<string, unknown>>;
function field<T = unknown>(row: Row | undefined, key: string): T | undefined { return row?.[key] as T | undefined; }
function text(row: Row | undefined, key: string): string { const value = field(row,key); return value === null || value === undefined ? "" : String(value); }
function number(row: Row | undefined, key: string): number { const value = Number(field(row,key) ?? 0); return Number.isFinite(value) ? value : 0; }
function date(value: unknown): string { if (!value || Number.isNaN(Date.parse(String(value)))) return "Not recorded"; return new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Johannesburg"}).format(new Date(String(value))); }
function human(value: string): string { return value.replaceAll(/[._-]+/g," ").replace(/\b\w/g,(letter)=>letter.toUpperCase()); }
function Pill({ value }: { value: string }) { return <span className={`commercial-pill ${value || "unknown"}`}>{human(value || "unknown")}</span>; }

async function mutate(operation: string, body: Readonly<Record<string, unknown>>) {
  const response = await fetch(`/api/commercial/${operation}`, { method:"POST", headers:{"content-type":"application/json","idempotency-key":`commercial-${crypto.randomUUID()}`}, body:JSON.stringify(body) });
  const result = await response.json() as Record<string,unknown> & { message?:string };
  if (!response.ok) throw new Error(result.message ?? "Commercial governance operation failed");
  return result;
}

export function CommercialGovernanceWorkspace({ commercial, tenants }: { commercial: CommercialGovernanceOverview; tenants: readonly TenantFleetItem[] }) {
  const router = useRouter();
  const [error,setError] = useState<string>(); const [message,setMessage] = useState<string>(); const [busy,setBusy] = useState<string>();
  const activePolicies = commercial.policies.filter((item)=>text(item,"lifecycle") === "active");
  const draftPolicies = commercial.policies.filter((item)=>["draft","scheduled"].includes(text(item,"lifecycle")));
  const activeModules = commercial.modules.filter((item)=>text(item,"status") === "active");
  const denialCount = commercial.denials.length;
  const modulesByPolicy = useMemo(()=>{
    const map = new Map<string,Row[]>();
    for (const module of commercial.policyModules) { const id=text(module,"planPolicyVersionId"); map.set(id,[...(map.get(id) ?? []),module]); }
    return map;
  },[commercial.policyModules]);

  async function run(operation:string,body:Readonly<Record<string,unknown>>,success:string){setBusy(operation);setError(undefined);setMessage(undefined);try{await mutate(operation,body);setMessage(success);router.refresh();return true;}catch(cause){setError(cause instanceof Error?cause.message:"Commercial governance operation failed");return false;}finally{setBusy(undefined);}}

  async function createPolicy(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);let limits:Record<string,unknown>;let modules:unknown[];try{limits=JSON.parse(String(data.get("limits")??"{}")) as Record<string,unknown>;modules=JSON.parse(String(data.get("modules")??"[]")) as unknown[];}catch{setError("Plan limits and module policy must be valid JSON.");return;}if(await run("policy:create",{planKey:String(data.get("planKey")),displayName:String(data.get("displayName")),description:String(data.get("description")),limits,defaultTrialDays:Number(data.get("defaultTrialDays")),effectiveFrom:new Date(String(data.get("effectiveFrom"))).toISOString(),effectiveUntil:data.get("effectiveUntil")?new Date(String(data.get("effectiveUntil"))).toISOString():undefined,billingProductReference:String(data.get("billingProductReference")??"")||undefined,reason:String(data.get("reason")),modules},"Draft plan policy created."))form.reset();}
  async function upsertModule(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);let quotaSchema:Record<string,unknown>;try{quotaSchema=JSON.parse(String(data.get("quotaSchema")??"{}")) as Record<string,unknown>;}catch{setError("Quota schema must be valid JSON.");return;}if(await run("module:upsert",{moduleKey:String(data.get("moduleKey")),displayName:String(data.get("displayName")),description:String(data.get("description")),category:String(data.get("category")),status:String(data.get("status")),quotaSchema,billingMetricKey:String(data.get("billingMetricKey")??"")||undefined,reason:String(data.get("reason"))},"Module catalogue updated."))form.reset();}
  async function transition(policy:Row,action:string){const reason=window.prompt(`Record why this plan policy is being ${action}.`);if(!reason||reason.trim().length<10){setError("A reason of at least 10 characters is required.");return;}await run(`policy:${text(policy,"id")}:transition`,{action,expectedVersion:number(policy,"version"),reason},`Plan policy ${action} recorded.`);}
  async function assignPlan(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const tenant=tenants.find((item)=>item.id===String(data.get("tenantId")));if(!tenant){setError("Select a tenant.");return;}if(await run(`tenant:${tenant.id}:plan`,{planKey:String(data.get("planKey")),policyVersionId:String(data.get("policyVersionId")),expectedTenantVersion:Number(data.get("expectedTenantVersion")),effectiveFrom:new Date(String(data.get("effectiveFrom"))).toISOString(),reason:String(data.get("reason"))},"Tenant plan assignment scheduled."))form.reset();}

  return <section className="commercial-governance" aria-labelledby="commercial-title">
    <header className="commercial-heading"><div><p className="cp-eyebrow">COMMERCIAL CONTROL</p><h1 id="commercial-title">Plans and entitlements</h1><p>Versioned packaging, module policy, quotas, trial windows, tenant assignments and denial evidence.</p></div><div className="commercial-generated"><small>Snapshot generated</small><strong>{date(commercial.generatedAt)}</strong></div></header>
    <div className="commercial-boundary"><strong>Effective-dated commercial policy</strong><p>Published plan baselines remain separate from tenant overrides. Future policy activates through the durable worker schedule, and every tenant denial retains a correlation identifier for diagnosis.</p></div>
    <section className="commercial-summary"><article><small>Plans</small><strong>{commercial.plans.length}</strong><span>{activePolicies.length} active policies</span></article><article><small>Module catalogue</small><strong>{commercial.modules.length}</strong><span>{activeModules.length} active modules</span></article><article><small>Pending governance</small><strong>{draftPolicies.length}</strong><span>Draft or scheduled policy</span></article><article className={denialCount?"warning":undefined}><small>Denial diagnostics</small><strong>{denialCount}</strong><span>Loaded recent events</span></article></section>
    {error?<p className="commercial-feedback error" role="alert">{error}</p>:null}{message?<p className="commercial-feedback success" role="status">{message}</p>:null}
    <nav className="commercial-index"><a href="#plans">Plans</a><a href="#policies">Policy versions</a><a href="#modules">Modules</a><a href="#assignments">Tenant assignments</a><a href="#denials">Denials</a><a href="#history">History</a></nav>

    <section id="plans" className="commercial-section"><header><div><p className="cp-eyebrow">PLAN REGISTER</p><h2>Current commercial products</h2></div><span>{commercial.plans.length}</span></header><div className="commercial-plan-grid">{commercial.plans.map((plan)=><article key={text(plan,"key")}><header><div><small>{text(plan,"key")}</small><h3>{text(plan,"displayName")}</h3></div><Pill value={field(plan,"active")?"active":"inactive"}/></header><div className="commercial-plan-adoption"><span><strong>{number(plan,"tenantCount")}</strong><small>Tenants</small></span><span><strong>{number(plan,"activeTenantCount")}</strong><small>Active</small></span><span><strong>{number(plan,"activePolicyVersion") || "None"}</strong><small>Policy version</small></span></div><dl>{Object.entries((field(plan,"limits") as Record<string,unknown>|undefined)??{}).map(([key,value])=><div key={key}><dt>{human(key)}</dt><dd>{String(value)}</dd></div>)}</dl><footer><span>Effective {date(field(plan,"effectiveFrom"))}</span><span>{text(plan,"billingProductReference")||"No billing product"}</span></footer></article>)}</div></section>

    <section id="policies" className="commercial-section"><header><div><p className="cp-eyebrow">POLICY VERSIONS</p><h2>Approval and effective-date workflow</h2></div><span>{commercial.policies.length}</span></header><div className="commercial-table-wrap"><table><thead><tr><th>Policy</th><th>Lifecycle</th><th>Modules</th><th>Effective period</th><th>Approval</th><th>Actions</th></tr></thead><tbody>{commercial.policies.map((policy)=>{const lifecycle=text(policy,"lifecycle");return <tr key={text(policy,"id")}><td><strong>{text(policy,"displayName")}</strong><small>{text(policy,"planKey")} v{number(policy,"versionNumber")}</small></td><td><Pill value={lifecycle}/></td><td>{number(policy,"moduleCount")}<small>{(modulesByPolicy.get(text(policy,"id"))??[]).map((item)=>text(item,"moduleKey")).join(", ")}</small></td><td>{date(field(policy,"effectiveFrom"))}<small>Until {date(field(policy,"effectiveUntil"))}</small></td><td>{text(policy,"approvedBy")?`Approved ${date(field(policy,"approvedAt"))}`:"Independent approval required"}</td><td><div className="commercial-row-actions">{lifecycle==="draft"&&!text(policy,"approvedBy")?<button onClick={()=>transition(policy,"approve")}>Approve</button>:null}{lifecycle==="draft"&&text(policy,"approvedBy")?<><button onClick={()=>transition(policy,"schedule")}>Schedule</button><button onClick={()=>transition(policy,"activate")}>Activate</button></>:null}{lifecycle==="scheduled"?<><button onClick={()=>transition(policy,"activate")}>Activate now</button><button onClick={()=>transition(policy,"cancel")}>Cancel</button></>:null}{lifecycle==="active"?<button className="danger" onClick={()=>transition(policy,"retire")}>Retire</button>:null}</div></td></tr>;})}</tbody></table></div>
      <form className="commercial-form" onSubmit={createPolicy}><h3>Create plan policy draft</h3><div className="commercial-form-grid three"><label>Plan key<input name="planKey" required placeholder="growth"/></label><label>Display name<input name="displayName" required/></label><label>Default trial days<input name="defaultTrialDays" type="number" min="0" max="365" defaultValue="0" required/></label></div><label>Description<textarea name="description" required minLength={20}/></label><label>Plan limits JSON<textarea name="limits" defaultValue={'{"activeLearners":5000,"storageBytes":107374182400}'}/></label><label>Module policy JSON<textarea name="modules" defaultValue={'[{"moduleKey":"core","state":"enabled","limits":{},"trialDays":0}]'}/><small>Array of moduleKey, state, limits and trialDays.</small></label><div className="commercial-form-grid"><label>Effective from<input name="effectiveFrom" type="datetime-local" required/></label><label>Effective until<input name="effectiveUntil" type="datetime-local"/></label></div><label>Billing product reference<input name="billingProductReference"/></label><label>Reason<textarea name="reason" required minLength={10}/></label><button disabled={Boolean(busy)}>Create policy draft</button></form>
    </section>

    <section id="modules" className="commercial-section"><header><div><p className="cp-eyebrow">MODULE CATALOGUE</p><h2>Capabilities, quotas and billing metrics</h2></div><span>{commercial.modules.length}</span></header><div className="commercial-module-grid">{commercial.modules.map((module)=><article key={text(module,"moduleKey")}><header><div><small>{text(module,"category")}</small><h3>{text(module,"displayName")}</h3></div><Pill value={text(module,"status")}/></header><p>{text(module,"description")}</p><code>{JSON.stringify(field(module,"quotaSchema")??{})}</code><footer>{text(module,"billingMetricKey")||"No billing metric"}</footer></article>)}</div><form className="commercial-form compact" onSubmit={upsertModule}><h3>Create or update module</h3><div className="commercial-form-grid three"><label>Module key<input name="moduleKey" required/></label><label>Display name<input name="displayName" required/></label><label>Category<select name="category"><option value="core">Core</option><option value="learning">Learning</option><option value="operations">Operations</option><option value="engagement">Engagement</option><option value="analytics">Analytics</option><option value="integration">Integration</option><option value="ai">AI</option></select></label></div><label>Description<textarea name="description" required minLength={20}/></label><div className="commercial-form-grid"><label>Status<select name="status"><option value="draft">Draft</option><option value="active">Active</option><option value="retired">Retired</option></select></label><label>Billing metric key<input name="billingMetricKey"/></label></div><label>Quota schema JSON<textarea name="quotaSchema" defaultValue="{}"/></label><label>Reason<textarea name="reason" required minLength={10}/></label><button disabled={Boolean(busy)}>Save module</button></form></section>

    <section id="assignments" className="commercial-section"><header><div><p className="cp-eyebrow">TENANT PLAN ASSIGNMENTS</p><h2>Scheduled commercial changes</h2></div><span>{commercial.assignments.length}</span></header><div className="commercial-table-wrap"><table><thead><tr><th>Tenant</th><th>Plan and policy</th><th>State</th><th>Effective</th><th>Evidence</th></tr></thead><tbody>{commercial.assignments.map((item)=><tr key={text(item,"id")}><td>{text(item,"tenantName")}<small>{text(item,"tenantId")}</small></td><td>{text(item,"planKey")}<small>{text(item,"planPolicyVersionId")}</small></td><td><Pill value={text(item,"state")}/></td><td>{date(field(item,"effectiveFrom"))}<small>Applied {date(field(item,"appliedAt"))}</small></td><td>{text(item,"reason")}<small>{text(item,"failureReason")}</small></td></tr>)}</tbody></table></div><form className="commercial-form compact" onSubmit={assignPlan}><h3>Schedule tenant plan change</h3><div className="commercial-form-grid"><label>Tenant<select name="tenantId" required><option value="">Select institution</option>{tenants.map((tenant)=><option key={tenant.id} value={tenant.id}>{tenant.displayName}</option>)}</select></label><label>Expected tenant version<input name="expectedTenantVersion" type="number" min="1" defaultValue="1" required/></label></div><div className="commercial-form-grid"><label>Plan key<input name="planKey" required/></label><label>Active policy<select name="policyVersionId" required><option value="">Select active policy</option>{activePolicies.map((policy)=><option key={text(policy,"id")} value={text(policy,"id")}>{text(policy,"planKey")} v{number(policy,"versionNumber")}</option>)}</select></label></div><label>Effective from<input name="effectiveFrom" type="datetime-local" required/></label><label>Reason<textarea name="reason" required minLength={10}/></label><button disabled={Boolean(busy)}>Schedule assignment</button></form></section>

    <section id="denials" className="commercial-section"><header><div><p className="cp-eyebrow">DENIAL DIAGNOSTICS</p><h2>Entitlement enforcement evidence</h2></div><span>{commercial.denials.length}</span></header><div className="commercial-table-wrap"><table><thead><tr><th>Tenant</th><th>Module and capability</th><th>Denial</th><th>Correlation</th><th>Time</th></tr></thead><tbody>{commercial.denials.map((item,index)=><tr key={`${text(item,"correlationId")}:${index}`}><td>{text(item,"tenantName")}<small>{text(item,"tenantId")}</small></td><td>{human(text(item,"moduleKey"))}<small>{text(item,"capabilityKey")}</small></td><td><code>{text(item,"denialCode")}</code><small>{text(item,"reasonSummary")}</small></td><td><code>{text(item,"correlationId")}</code></td><td>{date(field(item,"deniedAt"))}</td></tr>)}</tbody></table></div></section>

    <section id="history" className="commercial-section"><header><div><p className="cp-eyebrow">CHANGE EVIDENCE</p><h2>Append-only commercial history</h2></div><span>{commercial.history.length}</span></header><div className="commercial-table-wrap"><table><thead><tr><th>Plan</th><th>Event</th><th>Reason</th><th>Actor</th><th>Occurred</th></tr></thead><tbody>{commercial.history.map((item)=><tr key={text(item,"id")}><td>{text(item,"planKey")}<small>{text(item,"policyVersionId")}</small></td><td><Pill value={text(item,"eventType")}/></td><td>{text(item,"reason")}</td><td><code>{text(item,"actorId")}</code></td><td>{date(field(item,"occurredAt"))}</td></tr>)}</tbody></table></div></section>
  </section>;
}
